### ISSUE TITLE
useFetch hook

### ISSUE THREAD

**Issue by gomorizsolt** [gomorizsolt/react-boilerplate#23]
Create a `useFetch` hook that comprises the following elements:
- provides an abstract interface that handles the data fetching and parsing,
- uses the built-in JS fetch(it might be different based on the users' preferences),
- sets an `isLoading` property to false/true based on the process.

[**Example gist**](https://gist.github.com/gomorizsolt/85e31485d1b138274299092ee6bfeb37).

**Comment by thisismydesign** [comment]
test

**Comment by thisismydesign** [comment]
test

**Comment by gomorizsolt** [comment]
Too specific use-case. Closed.
