### ISSUE TITLE
presets in .babelrc vs webpack config

### ISSUE THREAD

**Issue by ridhwaans** [gomorizsolt/react-boilerplate#25]
What is the advantage of putting babel presets in a .babelrc. 
```
{
    "presets": ["@babel/preset-env", "@babel/preset-react"],
```
or including them in webpack config in the modules section?
```
{
            test: /\.js$/i,
            use: [
                { 
                    loader: 'babel-loader',
                    options: { presets: ['@babel/env', '@babel/react'] }
                }
            ],
```

**Comment by gomorizsolt** [comment]
Hey @ridhwaans!

It's an interesting question. One reason might be that I have never seen a project that included the Babel related configs directly into Webpack. Moreover, I prefer placing these kinds of configuration files separately.

On the other hand, it might be a reasonable improvement. Are you aware of any advantages of doing it as you advised above?

**Comment by gomorizsolt** [comment]
Closed due to inactivity.

Feel free to re-open the issue if you'd like to discuss it.
