### ISSUE TITLE
Use c-hive/js-boilerplate as a base for generic JS concerns

### ISSUE THREAD

**Issue by thisismydesign** [gomorizsolt/react-boilerplate#37]
Looked at the generic parts of the boilerplate (e.g. vscode, eslint, prettier configs) and noticed it differs from what we use elsewhere: https://github.com/c-hive/js-boilerplate

Unless this is on purpose it would be nice to align these. AFAICT the result would actually be the same, but I did some cleanup since the version you're currently using.

**Comment by gomorizsolt** [comment]
Our conventions fit my preferences, so I'll adapt those to the project.

Thanks for the idea.

**Comment by gomorizsolt** [comment]
Resolved by #38.
