### ISSUE TITLE
Use preset config of eslint-plugin-react

### ISSUE THREAD

**Issue by thisismydesign** [gomorizsolt/react-boilerplate#46]
If I'm reading the readme right (https://github.com/yannickcr/eslint-plugin-react), using
```
    "plugins": [
        "react",
    ],
```
means you'd have to specify rules individually. Instead, it is recommended to use
```
  extends: [
    "plugin:react/recommended",
  ],
```

From my testing, it looks like the rules are in effect when using `extends` without using `plugins`.

**Comment by gomorizsolt** [comment]
Thanks for reporting this. What's the purpose of using the package as a plugin then? How does it affect the rules?

**Comment by gomorizsolt** [comment]
> This plugin exports a recommended configuration that enforces React good practices.

Sounds great. We can apply your proposal if these rules are indeed "good practices". :)

**Comment by thisismydesign** [comment]
> Thanks for reporting this. What's the purpose of using the package as a plugin then? How does it affect the rules?

I think it just makes the rules available.

**Comment by gomorizsolt** [comment]
Revised the set of rules the preset enables. Found [`react/display-name`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md) somewhat useless but the others definitely make sense.

**Comment by gomorizsolt** [comment]
Thanks for the suggestion, added the preset in #47.
